### ISSUE TITLE
InvalidOperationException in Microsoft.Data.Sqlite.dll in VS Output console

### ISSUE THREAD

**Issue by alexandrejobin** [Xabaril/AspNetCore.Diagnostics.HealthChecks#406]
When I use the HealthChecksUI, I get many exception in the visual studio output console:

```
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'System.InvalidOperationException' in Microsoft.Data.Sqlite.dll
...
...
// this one repeat many times
Exception thrown: 'System.InvalidOperationException' in Microsoft.Data.Sqlite.dll
```

To test it, just create a new aspnet core web project and add this in the startup.cs. No need to add anything in the Configure section. If you remove the `AddHealthChecksUI()` line, there's no error.
```
public void ConfigureServices(IServiceCollection services)
{
    services.AddControllersWithViews();

    services
        .AddHealthChecksUI()
        .AddHealthChecks();
}
```

Any idea?

**Comment by erwin-faceit** [comment]
Can this be related to this issue? 
https://github.com/dotnet/efcore/issues/18307

I've had this in the past (few months ago), but with the newest version of Visual Studio I'm not seeing these anymore.

**Comment by alexandrejobin** [comment]
I'm not able to get more information about the error so I can't say if it's related or not. The error seems to be logged only in the VS debug window and not in the application log. I can't trap it or if I can, I don't know how.

**Comment by ussamoo** [comment]
Same behavior here

**Comment by CarlosLanderas** [comment]
Could you provide some more information?

- Full Configuration
- Operative system
- Where are the UI is deployed (Azure WebApp, Docker Container, Permissions)
- User running the application

With only those two lines is pretty complicated to know what's going on.

Thanks!

**Comment by erwin-faceit** [comment]
> I'm not able to get more information about the error so I can't say if it's related or not. The error seems to be logged only in the VS debug window and not in the application log. I can't trap it or if I can, I don't know how.

Did you try to enable break when exceptions are thrown? I got the original exception by enabling that setting (got something with a NextResult). Go to Debug -> Exceptions, and in that window check the second checkbox (it should be partially checked). After you've found the exception, you can reset the settings with the right most button in that window.

**Comment by alexandrejobin** [comment]
This is what i get after enabling the break on exception.

```
Exception thrown: 'System.InvalidOperationException' in Microsoft.Data.Sqlite.dll
Invalid attempt to call NextResult when reader is closed.
```

**StackTrace**
`   at Microsoft.Data.Sqlite.SqliteDataReader.NextResult() in /_/src/Microsoft.Data.Sqlite.Core/SqliteDataReader.cs:line 134`

**My config**
- Visual Studio Professional 2019 v16.4.1
- .NET Core 3.1
- AspNetCore.HealthChecks.UI.Client 3.0.2
  - Microsoft.EntityFrameworkCore 3.0.0
  - Microsoft.EntityFrameworkCore.Sqlite 3.00
- Windows 10 1809 (17763.437) 
- The error happen in visual studio, not sure if it happen when published

**Comment by erwin-faceit** [comment]
Yep,  that's the one! Since you're using .NET Core 3.1, could you try updating both Microsoft.EntityFrameworkCore and Microsoft.EntityFrameworkCore.Sqlite to 3.1.0 or 3.1.1?

This issue was solved by a change in Visual Studio 16.4, but it also required a change in the Sqlite module to prevent this exception from showing up.

**Comment by alexandrejobin** [comment]
I can't upgrade since that HealthChecks depends on v3.0.0. I have listed the packages under AspNetCore.HealthChecks.UI.Client.

Or is there a way to force the library to use another version?

**Comment by erwin-faceit** [comment]
It depends on >= 3.0.0. You can just add the newer version of the nuget packages to your project directly, and they will be used instead.

**Comment by alexandrejobin** [comment]
I have installed Microsoft.EntityFrameworkCore.Sqlite v3.1.0 package and it solved the problem when the database get hit by HealthChecks (yeh) but I still get these errors at the initialization time even if I use v3.1.1.

```
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Projects\bookstore\src\BookStore.Web\bin\Debug\netcoreapp3.1\Microsoft.Data.Sqlite.dll'. Symbols loaded.
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Projects\bookstore\src\BookStore.Web\bin\Debug\netcoreapp3.1\SQLitePCLRaw.core.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Projects\bookstore\src\BookStore.Web\bin\Debug\netcoreapp3.1\SQLitePCLRaw.batteries_v2.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Projects\bookstore\src\BookStore.Web\bin\Debug\netcoreapp3.1\SQLitePCLRaw.provider.dynamic_cdecl.dll'. 
'iisexpress.exe' (CoreCLR: clrhost): Loaded 'C:\Projects\bookstore\src\BookStore.Web\bin\Debug\netcoreapp3.1\SQLitePCLRaw.nativelibrary.dll'. 
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
```

The exact error is
```
Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.Data.Sqlite.dll
SQLite Error 14: 'unable to open database file'.

Exception thrown: 'Microsoft.Data.Sqlite.SqliteException' in Microsoft.EntityFrameworkCore.Relational.dll
SQLite Error 14: 'unable to open database file'.
```

**Comment by erwin-faceit** [comment]
Now you're having a completely different issue. Your original issue seems to be solved by upgrading to 3.1.1.

For this issue, it happens if the connectionstring for the database is incorrect. HealthChecks UI has checks in place for that, and uses predefined values if no connectionstring is supplied. I would start by removing obj and bin directories. 

If you still experience this error, post a full stacktrace, and perhaps try the debugging trick again to locate the exact exception.

**Comment by alexandrejobin** [comment]
The error happen when calling `services.AddHealthChecksUI();`. I tried to inverse the calling of AddHealthChecksUI and AddHealthChecks but the error is still there.

```
public void ConfigureServices(IServiceCollection services)
{
    services.AddHttpContextAccessor();
    services.AddControllersWithViews();
    services.AddHealthChecksUI();
    services.AddHealthChecks();
}
```

```
SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) in /_/src/Microsoft.Data.Sqlite.Core/SqliteException.cs:line 85
```

```
SQLite Error 14: 'unable to open database file'.
   at Microsoft.Data.Sqlite.SqliteException.ThrowExceptionForRC(Int32 rc, sqlite3 db) in /_/src/Microsoft.Data.Sqlite.Core/SqliteException.cs:line 85
   at Microsoft.Data.Sqlite.SqliteConnection.Open() in /_/src/Microsoft.Data.Sqlite.Core/SqliteConnection.cs:line 242
   at Microsoft.EntityFrameworkCore.Storage.RelationalConnection.OpenDbConnection(Boolean errorsExpected) in /_/src/EFCore.Relational/Storage/RelationalConnection.cs:line 514
```

**Comment by CarlosLanderas** [comment]
@alexandrejobin are you still having this issue?

**Comment by alexandrejobin** [comment]
I have updated Microsoft.EntityFrameworkCore.Sqlite to v3.1.2 and still have the issue.
